<?php
/**
 * Created by PhpStorm.
 * User: gx
 * Date: 21/11/17
 * Time: 17.07
 */

namespace grptx\SEO;

use Yii;
use yii\base\Component;
use yii\web\View;

class SeoTag extends Component
{

    private $twitter;
    /** @var $facebook Facebook */
    private $facebook;
    private $site;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->facebook = new Facebook();
    }

    public function set($metas = [])
    {
        /** @var AbstractSeo $class */
        $class = null;
        foreach ($metas as $section => $values) {
            switch($section) {
                case 'facebook':
                    $class = new Facebook();
                    break;
                case 'twitter':
                    break;
                case 'site':
                    break;
            }
            $this->$class->set($values);
        }
    }

    public function render(){
        $this->facebook->render();
    }

    public function setAndRender($metas){
        $this->set($metas);
        $this->render();
    }
}